// action types
export const SET_LOGIN_USERNAME = "SET_LOGIN_USERNAME";
export const SET_LOGIN_PASSWORD = "SET_LOGIN_PASSWORD";
export const SET_SCREEN = "SET_SCREEN";
export const SET_HOSTNAME = "SET_HOSTNAME";
export const TRY_LOGIN = "TRY_LOGIN";
export const SET_LOGIN_OPEN_MENU = "SET_LOGIN_OPEN_MENU";
export const SET_GRUB_MAIN_SELECTED = "SET_GRUB_MAIN_SELECTED";

// screens
export const SCREEN_OFF = "SCREEN_OFF";
export const SCREEN_HIBERNATE = "SCREEN_HIBERNATE";
export const SCREEN_SUSPEND = "SCREEN_SUSPEND";
export const SCREEN_LOGIN = "SCREEN_LOGIN";
export const SCREEN_DIALOG_SHUTDOWN = "SCREEN_DIALOG_SHUTDOWN";
export const SCREEN_DIALOG_REBOOT = "SCREEN_DIALOG_REBOOT";
export const SCREEN_GRUB = "SCREEN_GRUB";
export const SCREEN_GRUB_ADVANCED = "SCREEN_GRUB_ADVANCED";
