export const DEBUG = false;

// action types
export const SET_LOGIN_USERNAME = "SET_LOGIN_USERNAME";
export const SET_LOGIN_PASSWORD = "SET_LOGIN_PASSWORD";
export const SET_SCREEN = "SET_SCREEN";
export const SET_HOSTNAME = "SET_HOSTNAME";
export const SET_LOGIN_OPEN_MENU = "SET_LOGIN_OPEN_MENU";
export const SET_GRUB_MAIN_SELECTED = "SET_GRUB_MAIN_SELECTED";
export const SET_GRUB_ADVANCED_SELECTED = "SET_GRUB_ADVANCED_SELECTED";
export const TRY_LOGIN = "TRY_LOGIN";
export const SET_KERNEL_AND_BOOT = "SET_KERNEL_AND_BOOT";
export const RESET_STATE = "RESET_STATE";

// power related screen
export const SCREEN_OFF = "SCREEN_OFF";
export const SCREEN_HIBERNATE = "SCREEN_HIBERNATE";
export const SCREEN_SUSPEND = "SCREEN_SUSPEND";
export const SCREEN_SHUTDOWN = "SCREEN_SHUTDOWN";
export const SCREEN_REBOOT = "SCREEN_REBOOT";
// normal screens
export const SCREEN_LOGIN = "SCREEN_LOGIN";
export const SCREEN_DIALOG_SHUTDOWN = "SCREEN_DIALOG_SHUTDOWN";
export const SCREEN_DIALOG_REBOOT = "SCREEN_DIALOG_REBOOT";
export const SCREEN_GRUB = "SCREEN_GRUB";
export const SCREEN_GRUB_ADVANCED = "SCREEN_GRUB_ADVANCED";
export const SCREEN_CONSOLE_BOOTING = "SCREEN_CONSOLE_BOOTING";
export const SCREEN_PLYMOUTH_PASSWORD = "SCREEN_PLYMOUTH_PASSWORD";
export const SCREEN_PLYMOUTH_BOOT = "SCREEN_PLYMOUTH_BOOT";
